### ISSUE TITLE
Incorrect SymLinking w/ MiSTer?

### ISSUE THREAD

**Issue by 40wattrange** [danmons/retronas#148]
I copied my files via the MiSTer share within RetroSMB

![image](https://user-images.githubusercontent.com/1192974/159206431-b3998921-9c00-4415-9130-7285a428a7a3.png)

but when I browse to retrosmb/retronas/roms/nintendo/snes the folder is empty.

![image](https://user-images.githubusercontent.com/1192974/159206362-5680d317-efd5-4f6c-a8b6-e363d796f85a.png)

I noticed that if I go to  retrosmb/retronas/roms/nintendo/wii - all the SNES files are there.

![image](https://user-images.githubusercontent.com/1192974/159206398-688a7ddc-e9a9-47d5-93cb-ced0406efd37.png)

**Comment by birdybro** [comment]
https://github.com/danmons/retronas/blob/1431f0c9eb6e970d8711d5d3405fcef754231768/ansible/retronas_systems.yml#L116

Try `retrosmb/retronas/roms/nintendo/superfamicom`?

**Comment by birdybro** [comment]
Oh looks like it was already fixed not too long ago

https://github.com/danmons/retronas/commit/1431f0c9eb6e970d8711d5d3405fcef754231768

**Comment by sairuk** [comment]
i missed it when i added the wii directory, surprised it hadn't come up until now. It was getting overriden

Update your romdirs from the Update menu it will fix the symlink

This was discovered as part of Discussion https://github.com/danmons/retronas/discussions/146 earlier today

**Comment by bbickell** [comment]
I'm also seeing the behavior above. Update via retronas.sh doesn't seem to fix SNES symlinks.

**Comment by sairuk** [comment]
Uh yeh, you should be reinstalling the Samba for Mister option from the Install menu to update the MiSTer specific links, not RomDir from Update menu as I mentioned above

before
```
lrwxrwxrwx 1 root     root       23 Apr  2 03:54  SNES -> ../../roms/nintendo/wii
```

after
```
lrwxrwxrwx 1 root     root       32 Apr  2 04:03  SNES -> ../../roms/nintendo/superfamicom

```

**Comment by bbickell** [comment]
Hey thanks for the clarification there. Did that and it resolved the issue
for me. Thanks!

**Comment by sairuk** [comment]
@40wattrange please also confirm and i'll close this issue out

**Comment by 40wattrange** [comment]
Sorry for not confirming. Everything is working fine on my end now and
corrected..
