### ISSUE TITLE
Xbox 360 top level symlink not working with share

### ISSUE THREAD

**Issue by jnackmclain** [danmons/retronas#45]
I can only access my Xbox 360 games via xbox360\games share
and not \roms\microsoft\xbox360

**Comment by MasterPhooey** [comment]
Yeah the Xbox360 symlink isn’t in the roms folder PS3 and PS2 create

**Comment by danmons** [comment]
I totally forgot this, sorry. 

I'm thinking of putting a `games` and `iso` sub folder below the generic `roms/microsoft/xbox360` folder, then linking the SMB share to the `games` location as the XBox360 expects decompresses games and not ISO images. 

There's similar breakdowns for PS2 and PS3 with different types of images or extracted games contents. 

I'll try and get this fix in over the next 24 hours.

**Comment by danmons** [comment]
Change committed for the share and symlinks to point to the generic ROMs dir. I'll test on a real 360 with Aurora Dash tomorrow.

**Comment by lilylarceny** [comment]
I am getting a symlinks error message on xbox360 SMB install, I believe it is related
![retronas error](https://user-images.githubusercontent.com/100004188/154778315-929693c7-8a5e-41a1-b5ef-ad20afeb0eb2.JPG)

**Comment by danmons** [comment]
This should be sorted now.  Re-running RetroNAS and the xbox360 config installer should fix it.

**Comment by sairuk** [comment]
@lilylarceny could you please confirm @danmons fix so we can close this issue off.

**Comment by jnackmclain** [comment]
I just re-ran the script and I got the same error and the xbox360 symlink is still not fixed
![image](https://user-images.githubusercontent.com/55568980/155586528-77b2cd36-9d8a-477a-985a-8186e6921109.png)

**Comment by sairuk** [comment]
very odd @jnackmclain , i have just run this tool here and it has created them properly

![image](https://user-images.githubusercontent.com/526372/155593636-d84937ee-b1a2-4ffd-9e32-140fedd8a419.png)

can you please run the following commands from the terminal and out the output here so we can confirm.

```
ls -lad /mnt/data/ext4/roms/microsoft/*
```

then we can check if the correct entries are available in retronas_systems.yml to create the dirs in the first instance

```
grep xbox360 /opt/retronas/ansible/retronas_systems.yml
```
correct output should be similar to the following
```
root@retroNAS:/data/retronas/roms/microsoft/xbox360# grep xbox360 /opt/retronas/ansible/retronas_systems.yml
  - { src: "microsoft/xbox360/iso", mister: "", retropie: "", batocera: "", recalbox: "", retroarch: "", ops2l: "", ps3netsrv: "", fspd: "" }
  - { src: "microsoft/xbox360/games", mister: "", retropie: "", batocera: "", recalbox: "", retroarch: "", ops2l: "", ps3netsrv: "", fspd: "" }
root@retroNAS:/data/retronas/roms/microsoft/xbox360# 
```

please also run and confirm the response

```
# cd /opt/retronas && git log -n1 | grep commit
commit a625e218c1c78f1566696f9803417f1bdb3d6f7a
```

**Comment by jnackmclain** [comment]
> > I just re-ran the script and I got the same error and the xbox360 symlink is still not fixed ![image](https://user-images.githubusercontent.com/55568980/155586528-77b2cd36-9d8a-477a-985a-8186e6921109.png)
> 
> 
> 
> Try renaming your "xbox360" top level dir to "xbox360_old" (you can do this in Cockpit) and re-running the XBox360 SMB config installer.  

Ah, yes I did this and reran the script and all is well now! No error and once I transferred the games back, they were available in both locations. Thank you
